/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminDashboard: typeof import('./src/components/App/AdminDashboard.vue')['default']
    ApiDocItem: typeof import('./src/components/App/ApiDocItem.vue')['default']
    BackOffice: typeof import('./src/components/template/BackOffice.vue')['default']
    CollapsableSection: typeof import('./src/components/UiLib/CollapsableSection.vue')['default']
    CollapsibleSection: typeof import('./src/components/UiLib/CollapsibleSection.vue')['default']
    CreateFolderDlg: typeof import('./src/components/App/FileExplorer/CreateFolderDlg.vue')['default']
    Emojis: typeof import('./src/components/UiLib/Emojis.vue')['default']
    FieldSpec: typeof import('./src/components/App/FieldSpec.vue')['default']
    File: typeof import('./src/components/App/FileExplorer/File.vue')['default']
    FileExplorer: typeof import('./src/components/App/FileExplorer/FileExplorer.vue')['default']
    FileUploadProgressDialog: typeof import('./src/components/UiLib/FileUpload/FileUploadProgressDialog.vue')['default']
    HLine: typeof import('./src/components/UiLib/HLine.vue')['default']
    Icon: typeof import('./src/components/UiLib/Icon.vue')['default']
    Imgx: typeof import('./src/components/UiLib/Imgx.vue')['default']
    ImgxSlide: typeof import('./src/components/UiLib/ImgxSlide.vue')['default']
    Load: typeof import('./src/components/UiLib/Load.vue')['default']
    LoadMore: typeof import('./src/components/UiLib/LoadMore.vue')['default']
    LogPresenter: typeof import('./src/components/App/SystemLog/LogPresenter.vue')['default']
    NoThrow: typeof import('./src/components/UiLib/NoThrow.vue')['default']
    Overlay: typeof import('./src/components/UiLib/Layer/Overlay.vue')['default']
    PageContent: typeof import('./src/components/App/PageContent.vue')['default']
    PageHeader: typeof import('./src/components/App/PageHeader.vue')['default']
    PagingToolbar: typeof import('./src/components/UiLib/PagingToolbar.vue')['default']
    ProgressCircular: typeof import('./src/components/UiLib/ProgressCircular.vue')['default']
    PulseBlock: typeof import('./src/components/UiLib/PulseBlock.vue')['default']
    Rating: typeof import('./src/components/UiLib/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/UiLib/Spacer.vue')['default']
    Switch: typeof import('./src/components/UiLib/Switch.vue')['default']
    System: typeof import('./src/components/UiLib/System/System.vue')['default']
    SystemConfig: typeof import('./src/components/App/SystemConfig.vue')['default']
    SystemLog: typeof import('./src/components/App/SystemLog/SystemLog.vue')['default']
    Tableu: typeof import('./src/components/UiLib/Tableu.vue')['default']
    Tablex: typeof import('./src/components/UiLib/Tablex.vue')['default']
    TimeFormat: typeof import('./src/components/UiLib/TimeFormat.vue')['default']
    TimeSpan: typeof import('./src/components/UiLib/TimeSpan.vue')['default']
    Tooltip: typeof import('./src/components/UiLib/Tooltip.vue')['default']
    Txt: typeof import('./src/components/UiLib/Txt.vue')['default']
    TxtArea: typeof import('./src/components/UiLib/TxtArea.vue')['default']
    Typing: typeof import('./src/components/App/Typing.vue')['default']
    UploadZone: typeof import('./src/components/UiLib/FileUpload/UploadZone.vue')['default']
    UserInfoDialog: typeof import('./src/components/App/UserInfoDialog.vue')['default']
  }
}
